---
sudo: true
services: docker

env:
  - distro: ubuntu1404
  - distro: ubuntu1604
  - distro: centos7

script:
  - export container_id=$(date +%s)
  - export cleanup=false

  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/djx339/4c0b0040e3b1d65810dbbd80c318a290/raw/
  - chmod +x ${PWD}/tests/test.sh

  - ${PWD}/tests/test.sh

  # Ensure docker-compose is installed
  - 'docker exec --tty ${container_id} env TERM=xterm which docker-compose'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
