---
- name: Get latest docker compose version
  uri: "url={{docker_compose_latest_api}} body_format={{docker_compose_api_body_format}} return_content=yes"
  register: _latest
  when: docker_compose_version is undefined or docker_compose_version is none or docker_compose_version|lower == "latest"

- name: Create docker_compose_url variable if did not specify version
  set_fact:
    docker_compose_url: "https://github.com/docker/compose/releases/download/{{ _latest|json_query('json.tag_name') }}/docker-compose-{{ansible_os_family}}-{{ansible_architecture}}"
  when: docker_compose_version is undefined or docker_compose_version is none or docker_compose_version|lower == "latest"

- name: Create docker_compose_url variable if specified version
  set_fact:
    docker_compose_url: "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-{{ansible_os_family}}-{{ansible_architecture}}"
  when: docker_compose_version is defined and docker_compose_version is not none and docker_compose_version|lower != "latest"

- name: Ensure parent folder of docker compose is exists
  file: "path={{docker_compose_file|dirname}} state=directory"

- name: Download docker compose
  get_url: "url={{docker_compose_url}} dest={{docker_compose_file}} mode=0755 validate_certs=no force=yes"

